Fix deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,8 +34,13 @@ jobs:
           ~/.cargo/bin/wasm-pack  # Cache wasm-pack binary
 
     - name: Install wasm-pack
-      if: !command -v wasm-pack
-      run: cargo install wasm-pack
+      run: |
+        if ! command -v wasm-pack &> /dev/null; then
+          echo "wasm-pack not found. Installing..."
+          cargo install wasm-pack
+        else
+          echo "wasm-pack is already installed."
+        fi
 
     - name: Install dependencies
       run: npm ci
